### ISSUE TITLE
Video overlay: Make container for team names have flexible width

### ISSUE THREAD

**Issue by annamontare-edu** [rollerderby/scoreboard#702]
At our tournament this weekend we had some team names that didn’t fit in the video overlay and appeared cut off.

## other solutions
I fixed it temporarily by setting a larger max width with OBS Studio’s option to add custom CSS. We could just increase the container width a little.

## desired solution
A variable width might work well, and adapt to whatever length the team names are. Might be a problem if someone adds names that are really long, but we could set a max value.

**Comment by jeddai** [comment]
What about something like this? Used an inner div and CSS keyframes to animate the name moving back and forth

```html
<!-- html/views/overlay/index.html -->
<div class="Team Row barBackground">
  <div class="Name VerticalCenter Box">
    <div class="NameInner" sbDisplay="AlternateName(overlay),Name"></div>
  </div>
  <!-- ... -->
```

```css
/* html/views/overlay/index.css */
.TeamBox .Team .Name { height: 1.24em; width: 67%; padding-left: 2%; border-left: 2px solid #666; }
.TeamBox .Team .Name .NameInner { display: inline-block; position: relative; min-width: 100%; font-size: 80%; animation: NameMove 14s ease-in-out infinite; }
@keyframes NameMove {
 10%, 100% { transform: translate(0, 0); left: 0; } 50%, 60% { transform: translate(-100%, 0); left: 100%; }
 }
```

https://github.com/user-attachments/assets/f7edef11-e2dc-474c-943c-68df5dc287d0

There's a small amount of jittering on it, going to try to iron that out but I personally think this could be a decent solution?
